openapi: 3.0.0
info:
  version: 0.0.1
  title: Driving School Distributed Management System
  description: 'The project for the courses "Laboratory of software systems" and "Distributed Systems"'
servers:
  - description: Base URL that should be replaced with the gateway URL
    url: "http://localhost:8000/"
paths:
  "/dossiers":
    post:
      summary: "Register a new subscriber's dossier"
      operationId: DossierRegistration
      tags: [DossierService]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubscriberDocuments"
      responses:
        "200":
          description: "Dossier is created. Returns id"
          content:
            text/plain:
              example: "64633c11f85fe95eb801c0b6"
        "400":
          description: "Bad request. Possible cases: 1) There are already a valid dossier with given fiscal code; 2) The subscriber age are not greater or equal to 16; 3) Subscriber name or surname contains numbers"
          content:
            text/plain:
              schema:
                type: string
                enum: [AGE_NOT_SUFFICIENT, VALID_DOSSIER_ALREADY_EXISTS, NAME_SURNAME_NOT_STRING]
        "500":
          $ref: '#/components/responses/ServerError'

  "/dossiers/{id}":
    get:
      summary: "Get the dossier information"
      operationId: DossierIdReading
      tags: [DossierService]
      parameters:
        - $ref: '#/components/parameters/DossierId'
      responses:
        "200":
          description: "Return all dossier information"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dossier"
        "500":
          $ref: '#/components/responses/ServerError'

  "/dossiers/{id}/examStatus":
      put:
        summary: "Update practical or theoretical exam status"
        operationId: updateExamStatus
        tags: [DossierService]
        parameters:
          - $ref: '#/components/parameters/DossierId'
        requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExamResult"
        responses:
          "200":
            description: "Successful exam state update"
          "400":
            $ref: '#/components/responses/BadRequest'
          "409":
            description: "Conflict: illegal update request"
            content:
              text/plain:
                schema:
                  type: string
                  enum: [ UPDATE_ERROR ]
          "500":
            $ref: '#/components/responses/ServerError'

  "/doctorSlots":
      post:
        summary: "Book a doctor visit"
        operationId: bookDoctorVisit
        tags: [DoctorService]
        requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DoctorSlot"
        responses:
          "200":
            description: "Registration successful"
            content:
              text/plain:
                schema:
                  type: string
                  enum: [ OK ]
          "400":
            description: "Bad request. Possible cases:
              1) Given dossier to book doctor slot not exist
              2) Given dossier has already booked a doctor slot in the future
              3) Given time is occupied by another doctor slot
              4) Given time does not respects doctors times
              5) Given day for the visit, is not a doctor day"
            content:
              text/plain:
                schema:
                  type: string
                  enum: [ DOSSIER_NOT_EXIST, DOSSIER_ALREADY_BOOKED, TIME_OCCUPIED, BAD_TIME, NOT_DOCTOR_DAY ]
      get:
        summary: "Get booked doctor slots"
        operationId: getBookedDoctorSlots
        tags: [DoctorService]
        requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBookedDoctorSlots"
        responses:
          "200":
            description: "Ok. Possible cases:
              1) No slots occupied in the given date
              2) Slots occupied given as a response"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/DoctorSlot"
              text/plain:
                schema:
                  type: string
                  enum: [NO_SLOT_OCCUPIED, OK]
          "400":
            description: "Bad request: there was an error during serialization of given object"
      put:
        summary: "Register doctor visit result"
        operationId: saveDoctorResult
        tags: [DoctorService]
        requestBody:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DoctorResult"
        responses:
          "200":
            description: "Result has been acknowledged"
          "400":
            description: "Bad request. Possible cases:
              1) Serialization exception
              2) Insert error from server"

  "/doctorSlots/{id}":
    delete:
      summary: "Delete booked doctor slot for a dossier id"
      operationId: deleteDoctorSlot
      tags: [DoctorService]
      parameters:
        - $ref: '#/components/parameters/DossierId'
      responses:
        "200":
          description: "Ok. Delete was successful"
        "400":
          description: "Bad request. There was some delete error"


  "/api/{id}":
    get:
      summary: "Get a user by id"
      operationId: test
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: "10"
      responses:
        "200":
          description: ""
          content:
            text/plaintext:
              schema:
                type: string


components:
  schemas:
    SubscriberDocuments:
      type: object
      required: [name, surname, birthdate, fiscal_code]
      properties:
        name:
          type: string
          example: "Homer"
        surname:
          type: string
          example: "Simpsons"
        birthdate:
          type: string
          format: date
          example: "1990-03-03"
        fiscal_code:
          type: string
          example: "SMPHMR80A01C573O"
    Dossier:
      allOf:
        - $ref: '#/components/schemas/SubscriberDocuments'
        - type: object
          required: [_id, validity, examAttempts]
          properties:
            _id:
              type: string
              example: "64633c11f85fe95eb801c0b6"
            validity:
              type: boolean
            examsStatus:
              $ref: '#/components/schemas/ExamsStatus'
    ExamsStatus:
      type: object
      required: [theoreticalExamState,practicalExamState]
      properties:
        theoreticalExamState:
          type: string
          enum: [TO_DO, PASSED]
        practicalExamState:
          type: string
          enum: [TO_DO, FIRST_PROVISIONAL_LICENCE_INVALID, SECOND_PROVISIONAL_LICENCE_INVALID, PASSED]
    ExamResult:
      type: object
      required: [exam, outcome]
      properties:
        exam:
          type: string
          enum: [THEORETICAL, PRACTICAL]
        outcome:
          type: string
          enum: [PASSED, FAIL]
    DoctorSlot:
      type: object
      required: [date, time, dossierId]
      properties:
        date:
          type: string
          example: "2023-10-12"
          enum: [TUESDAY, FRIDAY]
        time:
          type: string
          example: "9:30"
          description: "Must be between 18:00 and 19:30"
        dossierId:
          type: string
          example: "64633c11f85fe95eb801c0b6"
    GetBookedDoctorSlots:
      type: object
      required: [date]
      properties:
        date:
          type: string
          example: "2023-10-12"
    DoctorResult:
      type: object
      required: [dossierId, date, result]
      properties:
        date:
          type: string
          example: "2023-10-12"
        dossierId:
          type: string
          example: "64633c11f85fe95eb801c0b6"
        result:
          type: string
          enum: [VALID, NEED_ONE_MORE_VISIT, NOT_VALID]

  parameters:
    DossierId:
      name: id
      in: path
      description: id of the dossier
      required: true
      schema:
        type: string
        example: "d1"


  responses:
    ServerError:
      description: Internal server error that typically happen when there are an error in server source code
      content:
        text/plain:
          example: "IllegalStateException message"
    BadRequest:
      description: The request to the server not conform to the requested format
      content:
        text/plain:
          example: "Exception message"
#    PracticalExamAttempts:
#      type: object
#      required: [attempts]
#      properties:
#        attempts:
#          type: integer
#    ExamStatus:
#      type: object
#      required: [theoreticalExam, practicalExam]
#      properties:
#        practical:
#          type: boolean
#        theoretical:
#          type: boolean
