title: "DSDMS"
#remote_theme: pages-themes/slate@v0.2.0
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"

show_downloads: false

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.2.2"
