name: main workflow

on: 
    push:
        branches:
            - main
            - develop
        paths-ignore:
            - "report/*"
            - 'README.md'
            - 'CHANGELOG.md'
            - 'LICENSE'

jobs: 
    firstJob:
        strategy:
            matrix:
                os: [ ubuntu-latest ] #windows-latest
        runs-on: ${{ matrix.os }} # Operating system selection
        steps:
            - run: echo "Hello World"