name: main workflow

on: 
    push:
        branches:
            - main
            - develop
        paths-ignore:
            - "report/*"
            - 'README.md'
            - 'CHANGELOG.md'
            - 'LICENSE'

jobs: 
    firstJob:
        strategy:
            matrix:
                os: [ ubuntu-latest ] #windows-latest
        runs-on: ${{ matrix.os }} # Operating system selection
        steps:
            - run: echo "Hello World"
            - name: Checkout
              uses: actions/checkout@v2
            - uses: actions/setup-java@v1 # Add this step (if possible)
              with:
                java-version: "16"
            - name: Setup kotlin
              uses: fwilhe2/setup-kotlin@main
            - name: run tests
              run: | 
                  ./gradlew DossierService:run &
                  sleep 5 &&
                  ./gradlew cucumber