name: publish openapi latest version on SwaggerHub

on:
  push:
    paths:
      - 'docs/src/api/*'
      
jobs:
  swagger:
    runs-on: ubuntu-latest
    env:
      SRCFILE: ./docs/src/api/openapi.yaml
      FILE: ./build/openapi/openapi.yaml
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: ./.github/workflows/swaggerhub-publish
        with:
          token: ${{ secrets.SWAGGERHUB_TOKEN }}
          type: update